
spring:
  datasource:
    url: jdbc:h2:mem:solarOffGrid
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console:
      enabled: true
  server:
    port: ${SERVER_PORT:8080}