CREATE TABLE  IF NOT EXISTS LOCALIZACAO_CIDADE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    municipio VARCHAR(255) NOT NULL,
    mun_uf VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    uf VARCHAR(10) NOT NULL,
    valor VARCHAR(100) NOT NULL
);

