CREATE TABLE  IF NOT EXISTS IRRADIACAO_SOLAR (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION,
    media_anual DOUBLE PRECISION,
    janeiro DOUBLE PRECISION,
    fervereiro DOUBLE PRECISION,
    marco DOUBLE PRECISION,
    abril DOUBLE PRECISION,
    maio DOUBLE PRECISION,
    junho DOUBLE PRECISION,
    julho DOUBLE PRECISION,
    agosto DOUBLE PRECISION,
    setembro DOUBLE PRECISION,
    outubro DOUBLE PRECISION,
    novembro DOUBLE PRECISION,
    dezembro DOUBLE PRECISION
);