CREATE TABLE  IF NOT EXISTS FATOR_CORRECAO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    latitude DOUBLE PRECISION,
    identificacao DOUBLE PRECISION,
    inclinacao DOUBLE PRECISION,
    jan DOUBLE PRECISION,
    fev DOUBLE PRECISION,
    mar DOUBLE PRECISION,
    abr DOUBLE PRECISION,
    mai DOUBLE PRECISION,
    jun DOUBLE PRECISION,
    jul DOUBLE PRECISION,
    ago DOUBLE PRECISION,
    sett DOUBLE PRECISION,
    out DOUBLE PRECISION,
    nov DOUBLE PRECISION,
    dez DOUBLE PRECISION
);